name: Tests
on: [push, pull_request]
jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests in mixed data persistence (critical tests in real infrastructure, other in-memory)
        run: npm test

      - name: Run tests in-memory
        run: npm run test:inmemory

      - name: Run tests with Sqlite3 database
        run: npm run test:sqlite3
